name: Format .NET code
on: [pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.103'
      - name: Add dotnet-format-problem-matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1
      - name: Restore .NET tools
        uses: xt0rted/dotnet-tool-restore@v1
      - name: Format .NET code
        run: dotnet format
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: Studio Rv & Co
          author_email: studio.rvandco@gmail.com
          message: 'Format dotnet code'
          add: '*.cs'
