name: Lint

on: [ push, pull_request ]

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: super-linter/super-linter@v5
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v3
      - run: |
          dotnet tool restore
          dotnet csharpier --check .